services:
  mysql:
    image: mysql:9.6.0
    container_name: lightframe-mysql
    restart: unless-stopped
    env_file:
      - ./backend/.env
    command: --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "--password=$${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./lightframe
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    env_file:
      - ./backend/.env
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/iain
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network


volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge