services:
  frontend:
    build:
      context: ./lightframe
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    # env_file:
    #   - ./lightframe/.env

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ~/.oci:/root/.oci
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge