services:
  frontend:
    build:
      context: ./lightframe
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network
    # env_file:
    #   - ./lightframe/.env


  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.oci:/root/.oci
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81" # Web UI
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - app-network


networks:
  app-network:

    driver: bridge