spring.config.import=optional:file:.env[.properties]
spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=false

auth.secret_key=${SECRET_KEY}
auth.password=${ADMIN_PASSWORD}

r2.account.id=${R2_ACCOUNT_ID}
r2.access.key.id=${R2_ACCESS_KEY_ID}
r2.secret.access.key=${R2_SECRET_ACCESS_KEY}
r2.bucket.name=${R2_BUCKET_NAME}
